abstract class RatingAndFeedbackState{}
class InitialRatingAndFeedbackState extends RatingAndFeedbackState{}
class RatingUpdatedState extends RatingAndFeedbackState{}
class RatingAndFeedbackSubmitedState extends RatingAndFeedbackState{}